"name" : "dart_pbkdf2"
"version" : "0.2.1"
"author" : "Robin Harper <cabrel@zerklabs.com>"
"description" : "PBKDF2 implementation in Dart"
"homepage" : "https://github.com/cabrel/dart-pbkdf2"
"dependencies" :
  "crypto" : ">=0.9.0"
  "fixnum" : ">=0.9.0"
  "utf" : ">=0.9.0"
  "unittest" : ">=0.9.0"
  "sequence_zip" : ">=0.9.0"
